import{createHash}from"node:crypto";import{authorizeOverride,dueOutreachIntervals,evaluateBindReadiness,groundedClaimsDraft,renewalRisk,type Fulfillment,type Requirement,type Role}from"./domain.ts";
type Policy={id:string;status:"bind_requested"|"bound";requirements:Requirement[];fulfillments:Fulfillment[];overrides:{justification:string;actorRole:Role;fingerprint:string;createdAt:string}[]};
type Claim={id:string;policyId:string;rawStatement:string;draft:ReturnType<typeof groundedClaimsDraft>|Record<string,unknown>;status:"drafting"|"reviewed";reviewedAt?:string};
type Renewal={id:string;client:string;line:string;days:number;loggedIntervals:number[];responseReceived:boolean};
const seedPolicy=():Policy=>({id:"POL-1048",status:"bind_requested",requirements:[{id:"REQ-1",name:"Signed application",type:"attestation",mandatory:true},{id:"REQ-2",name:"Prior coverage declarations",type:"prior_coverage_proof",mandatory:true},{id:"REQ-3",name:"Roof inspection photos",type:"inspection_photo",mandatory:true},{id:"REQ-4",name:"Smart-home discount form",type:"document_upload",mandatory:false}],fulfillments:[{requirementId:"REQ-1",fulfilled:true,evidence:"Application signed July 21, 2026"},{requirementId:"REQ-2",fulfilled:true,evidence:"Travelers declarations uploaded"}],overrides:[]});
const seedRenewals=():Renewal[]=>[{id:"POL-8821",client:"Maya Chen",line:"Commercial package",days:9,loggedIntervals:[60,30],responseReceived:false},{id:"POL-7314",client:"Northline Bakery",line:"Business owners",days:26,loggedIntervals:[60],responseReceived:false},{id:"POL-6620",client:"Luis Alvarez",line:"Personal auto",days:48,loggedIntervals:[60],responseReceived:false},{id:"POL-5402",client:"Iris Hammond",line:"Homeowners",days:-1,loggedIntervals:[60,30,10],responseReceived:false}];
type State={policies:Map<string,Policy>;claims:Map<string,Claim>;renewals:Renewal[]};const globalStore=globalThis as typeof globalThis&{__vowrailStore?:State};
function createState():State{return{policies:new Map([["POL-1048",seedPolicy()]]),claims:new Map(),renewals:seedRenewals()}}export function store(){return globalStore.__vowrailStore??=(createState())}export function resetStore(){globalStore.__vowrailStore=createState()}
export function fingerprint(value:unknown){return createHash("sha256").update(JSON.stringify(value)).digest("hex")}
export function policySnapshot(id:string){const policy=store().policies.get(id);if(!policy)return null;return{...policy,decision:evaluateBindReadiness(policy.requirements,policy.fulfillments)}}
export function fulfillRequirement(policyId:string,requirementId:string,evidence:string){const policy=store().policies.get(policyId);if(!policy)throw new Error("Policy not found");const requirement=policy.requirements.find(item=>item.id===requirementId);if(!requirement)throw new Error("Requirement not found");if(policy.fulfillments.some(item=>item.requirementId===requirementId&&item.fulfilled))return policySnapshot(policyId);policy.fulfillments.push({requirementId,fulfilled:true,evidence:`${evidence} · sha256:${fingerprint(evidence).slice(0,12)}`});return policySnapshot(policyId)}
export function bindPolicy(policyId:string){const policy=store().policies.get(policyId);if(!policy)throw new Error("Policy not found");const decision=evaluateBindReadiness(policy.requirements,policy.fulfillments);if(!decision.canBind)return{ok:false,status:policy.status,missingRequirements:decision.missingRequirements};policy.status="bound";return{ok:true,status:policy.status,method:"requirements_satisfied",fingerprint:fingerprint(policy)}}
export function overrideAndBind(policyId:string,role:Role,delegated:boolean,justification:string){const policy=store().policies.get(policyId);if(!policy)throw new Error("Policy not found");const authorization=authorizeOverride(role,delegated,justification);if(!authorization.allowed)return{ok:false,reason:authorization.reason};const record={justification,actorRole:role,fingerprint:fingerprint({policyId,role,justification,at:new Date().toISOString()}),createdAt:new Date().toISOString()};policy.overrides.push(record);policy.status="bound";return{ok:true,status:policy.status,method:"documented_override",record}}
export function createClaim(policyId:string,rawStatement:string,draft?:Record<string,unknown>){const id=`CLM-${Date.now()}`;const claim:Claim={id,policyId,rawStatement,draft:draft??groundedClaimsDraft(rawStatement),status:"drafting"};store().claims.set(id,claim);return claim}export function finalizeClaim(id:string){const claim=store().claims.get(id);if(!claim)throw new Error("Claim not found");claim.status="reviewed";claim.reviewedAt=new Date().toISOString();return claim}
export function renewalSnapshot(){return store().renewals.map(item=>({...item,risk:renewalRisk(item.days,item.responseReceived)}))}
export function runRenewalSweep(){const actions:{policyId:string;interval:number;idempotencyKey:string}[]=[];for(const policy of store().renewals){for(const interval of dueOutreachIntervals(policy.days,policy.loggedIntervals)){policy.loggedIntervals.push(interval);actions.push({policyId:policy.id,interval,idempotencyKey:`${policy.id}:${interval}`})}}return{evaluated:store().renewals.length,actions,atRisk:renewalSnapshot().filter(item=>item.risk==="high"||item.risk==="critical").length}}
