[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.devnet]
vowrail_policy = "7Pn6g5g88YzD5aJyCzrftCwQqCWm8bxYxPpUC2xURG2V"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/*"]
