"use client";

import { useEffect, useMemo, useState } from "react";
import { CheckCircle2, ExternalLink, RefreshCw, Search } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { WalletButton } from "@/components/wallet-button";

type Receipt={address:string;version:number;policy:string;mandateHash:string;provider:string;amountSol:number;slippageBps:number|null;recordedAt:number;signature:string|null;slot:number|null};
async function fetchReceipts(){const response=await fetch("/api/receipts",{cache:"no-store"});const data=await response.json();if(!response.ok)throw new Error(data.detail??data.error);return data.receipts??[]}

export default function Receipts(){
  const[receipts,setReceipts]=useState<Receipt[]>([]);const[policyAddress,setPolicyAddress]=useState("");const[query,setQuery]=useState("");const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[verified,setVerified]=useState<Record<string,string>>({});
  const load=async()=>{setLoading(true);setError("");try{setReceipts(await fetchReceipts())}catch(nextError){setError(nextError instanceof Error?nextError.message:"Unable to load receipts")}finally{setLoading(false)}};
  useEffect(()=>{let active=true;fetchReceipts().then(data=>{if(active)setReceipts(data)}).catch(nextError=>{if(active)setError(nextError instanceof Error?nextError.message:"Unable to load receipts")}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[]);
  const connect=async(authority:string)=>{const response=await fetch(`/api/policy?authority=${authority}`);const data=await response.json();setPolicyAddress(data.exists?data.address:"missing")};
  const verify=async(receipt:Receipt)=>{if(!receipt.signature)return;setVerified(current=>({...current,[receipt.address]:"CHECKING"}));const response=await fetch("/api/verify",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({signature:receipt.signature})});const data=await response.json();setVerified(current=>({...current,[receipt.address]:data.verified?`CONFIRMED SLOT ${data.slot}`:"NOT VERIFIED"}))};
  const filtered=useMemo(()=>receipts.filter(receipt=>{const wallet=!policyAddress||policyAddress==="missing"||receipt.policy===policyAddress;const text=`${receipt.address} ${receipt.policy} ${receipt.provider} ${receipt.mandateHash}`.toLowerCase();return wallet&&text.includes(query.toLowerCase())}),[receipts,policyAddress,query]);
  return <AppShell active="/receipts"><div className="topbar"><div><h1>Proof receipts</h1><p>V1 and V2 program accounts decoded from devnet, with independent transaction verification.</p></div><WalletButton onConnected={connect}/></div><section className="card"><div className="panel-title"><div><h2>Receipt index</h2><p className="subtle">Program 7Pn6...URG2V / newest first</p></div><div className="receipt-tools"><label className="search"><Search size={15}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search address, provider, hash" aria-label="Search receipts"/></label><button className="icon-button" onClick={load} aria-label="Refresh receipts"><RefreshCw size={16}/></button></div></div>{policyAddress==="missing"&&<div className="notice">The connected wallet has no V2 policy PDA yet. Showing every public receipt.</div>}{error?<Empty title="RPC read failed" copy={error}/>:loading?<Empty title="Reading program accounts" copy="Fetching and decoding receipt PDAs from Solana devnet."/>:filtered.length===0?<Empty title="No matching receipts" copy="Create an approved receipt in Policy Studio or clear the active search."/>:<div className="receipt-list">{filtered.map(receipt=><article className="receipt-card" key={receipt.address}><div className="receipt-status"><i/>V{receipt.version} VERIFIED ACCOUNT</div><div className="receipt-hash mono">{receipt.mandateHash}</div><div className="receipt-grid"><Item label="Receipt PDA" value={receipt.address}/><Item label="Policy PDA" value={receipt.policy}/><Item label="Provider program" value={receipt.provider}/><Item label="Approved amount" value={`${receipt.amountSol.toFixed(3)} SOL`}/><Item label="On-chain slippage" value={receipt.slippageBps===null?"V1 unavailable":`${receipt.slippageBps} BPS`}/><Item label="Recorded" value={new Date(receipt.recordedAt*1000).toLocaleString()}/><Item label="Slot" value={String(receipt.slot??"indexing")}/></div>{receipt.signature&&<div className="receipt-actions"><button className="button small" onClick={()=>verify(receipt)}><CheckCircle2 size={14}/>Verify through RPC</button><a className="button small" target="_blank" rel="noreferrer" href={`https://explorer.solana.com/tx/${receipt.signature}?cluster=devnet`}>Explorer <ExternalLink size={14}/></a>{verified[receipt.address]&&<span className="verify-note">{verified[receipt.address]}</span>}</div>}</article>)}</div>}</section></AppShell>;
}
function Empty({title,copy}:{title:string;copy:string}){return <div className="empty-state"><b>{title}</b><p>{copy}</p></div>}
function Item({label,value}:{label:string;value:string}){return <div><span>{label}</span><b className="mono">{value}</b></div>}
