import Link from "next/link";
import { ArrowRight, Braces, FileCheck2, KeyRound, Shield, WalletCards, Waypoints } from "lucide-react";
import { SiteNav } from "@/components/site-nav";
import { Reveal } from "@/components/motion";

const features=[
  [Braces,"Mandate compiler","Convert operator limits into deterministic policy an agent cannot reinterpret.","HUMAN INTENT -> POLICY"],
  [KeyRound,"Provider-verifiable proof","A paid service can validate the receipt account before releasing its protected resource.","RECEIPT -> ACCESS"],
  [FileCheck2,"Portable evidence","Bind policy, mandate hash, provider, amount, slippage, and time in a public Solana account.","DECISION -> PUBLIC EVIDENCE"],
] as const;

export default function Home(){return <><SiteNav/><main><section className="hero shell"><Reveal><span className="eyebrow">Proof-carrying policy for autonomous agents</span><h1>Agents move fast. Capital needs lines.</h1><p className="hero-copy">Vowrail turns a human mandate into machine-checkable limits. Every paid intent is normalized, checked, and bound to a provider-verifiable receipt before protected work is released.</p><div className="hero-actions"><Link className="button primary" href="/studio">Build a mandate <ArrowRight size={16}/></Link><Link className="button" href="/lab">Run the 402 checkout</Link></div><div className="microproof"><div><b>V2</b>on-chain policy</div><div><b>5</b>hard boundaries</div><div><b>Devnet</b>receipt-gated access</div></div></Reveal><Reveal className="rail-stage" delay={0.12}><div className="orb one"/><div className="orb two"/><div className="rail-card"><div className="terminal-head"><span>MANDATE / 0x7A91</span><span className="status"><i/> POLICY V2</span></div><div className="intent"><small>Agent request</small><p>Buy a 0.1 SOL risk dataset from an allowlisted provider before mandate expiry.</p></div><div className="checks"><div className="check"><span>Provider allowlist</span><span className="pass">PASS</span></div><div className="check"><span>Per-call ceiling</span><span className="pass">PASS</span></div><div className="check"><span>Daily budget</span><span className="pass">PASS</span></div><div className="check"><span>Policy expiry</span><span className="pass">PASS</span></div><div className="check"><span>Slippage ceiling</span><span className="pass">PASS</span></div></div><div className="receipt">RECEIPT READY - provider may release resource</div></div></Reveal></section>
<section id="product" className="section shell"><div className="section-head"><div><span className="eyebrow">The evidence rail</span><h2>Control is useful. Verifiable control travels further.</h2></div><p>Wallet controls stop at the wallet. Vowrail produces a proof object that an agent, provider, operator, or auditor can independently inspect before trusting the transaction outcome.</p></div><div className="grid-3">{features.map(([Icon,title,copy,tag])=><article className="feature" key={title}><div className="feature-icon"><Icon size={20}/></div><h3>{title}</h3><p>{copy}</p><span className="tag">{tag}</span></article>)}</div></section>
<section id="workflow" className="dark-section"><div className="shell"><div className="section-head"><div><span className="eyebrow">Deterministic by design</span><h2>No invisible leap from prompt to paid output.</h2></div><p>The model may explain a decision. It cannot grant authority, modify a limit, add a provider, or create a receipt for a denied intent.</p></div><div className="workflow"><article><span>01 / CHALLENGE</span><h3>Receive the quote</h3><p>The provider returns a typed 402 mandate with price, identity, resource, and expiry.</p></article><article><span>02 / ENFORCE</span><h3>Check the policy</h3><p>Provider, value, daily spend, slippage, and expiry are enforced deterministically.</p></article><article><span>03 / ATTEST</span><h3>Create the receipt</h3><p>An approved intent becomes a PDA bound to the policy and mandate hash.</p></article><article><span>04 / RELEASE</span><h3>Verify before serving</h3><p>The provider reads the receipt account and only then releases the protected resource.</p></article></div></div></section>
<section id="proof" className="section shell"><div className="section-head"><div><span className="eyebrow">Built for operators and providers</span><h2>A policy decision that can answer why and prove where.</h2></div><p>The V2 account records the provider, amount, slippage, mandate hash, policy account, and timestamp under one stable program ID.</p></div><div className="grid-3"><article className="feature"><div className="feature-icon"><Shield size={20}/></div><h3>Default deny</h3><p>Unknown providers and expired mandates fail on-chain instead of inheriting wallet access.</p></article><article className="feature"><div className="feature-icon"><WalletCards size={20}/></div><h3>Non-custodial</h3><p>The connected wallet signs directly. Vowrail never receives the operator private key.</p></article><article className="feature"><div className="feature-icon"><Waypoints size={20}/></div><h3>Rail-agnostic mandate</h3><p>The evidence model can sit behind x402 or direct Solana workflows without becoming a wallet.</p></article></div></section><section className="cta shell"><div className="cta-card"><h2>Run the entire challenge-to-release loop.</h2><div className="hero-actions" style={{justifyContent:"center"}}><Link className="button primary" href="/lab">Open checkout lab <ArrowRight size={16}/></Link><Link className="button" href="/receipts">Inspect live receipts</Link></div></div></section></main><footer className="footer shell"><span>Vowrail - Solana devnet V2</span><span>Mandate. Enforce. Prove. Release.</span></footer></>}
