import Link from "next/link";
import { ArrowRight, Braces, FileCheck2, ScanSearch, Shield, WalletCards, Waypoints } from "lucide-react";
import { SiteNav } from "@/components/site-nav";

const features=[
  [Braces,"Mandate compiler","Convert operating limits into deterministic JSON policy an agent cannot reinterpret.","HUMAN INTENT -> POLICY"],
  [ScanSearch,"Transaction lens","Decode programs, token movement, signer changes, and side effects before signing.","RAW BYTES -> EXPLAINED ACTION"],
  [FileCheck2,"Proof receipt","Hash the policy and decision, then anchor a compact receipt on Solana devnet.","DECISION -> PUBLIC EVIDENCE"],
] as const;

export default function Home(){return <><SiteNav/><main><section className="hero shell"><div><span className="eyebrow">Execution policy for autonomous agents</span><h1>Agents move fast. Capital needs lines.</h1><p className="hero-copy">Vowrail turns a human mandate into machine-checkable transaction rules. Every proposed action is decoded, simulated, scored, and recorded before it reaches Solana.</p><div className="hero-actions"><Link className="button primary" href="/studio">Build a mandate <ArrowRight size={16}/></Link><a className="button" href="#workflow">See the execution path</a></div><div className="microproof"><div><b>4</b>enforcement stages</div><div><b>&lt;1s</b>local policy check</div><div><b>Devnet</b>proof receipts</div></div></div><div className="rail-stage"><div className="orb one"/><div className="orb two"/><div className="rail-card"><div className="terminal-head"><span>INTENT / 0x7A91</span><span className="status"><i/> POLICY LIVE</span></div><div className="intent"><small>Agent request</small><p>Swap 2.4 SOL to USDC through Jupiter. Maximum price impact 0.35%.</p></div><div className="checks"><div className="check"><span>Program allowlist</span><span className="pass">PASS</span></div><div className="check"><span>Notional ceiling</span><span className="pass">PASS</span></div><div className="check"><span>Simulation delta</span><span className="pass">PASS</span></div><div className="check"><span>Destination screen</span><span className="pass">PASS</span></div></div><div className="receipt">READY - policy hash 84c1...f209</div></div></div></section>
<section id="product" className="section shell"><div className="section-head"><div><span className="eyebrow">The control plane</span><h2>One rail from intent to evidence.</h2></div><p>Wallet permissions are blunt. Vowrail evaluates the meaning of a transaction: which programs it calls, what leaves the wallet, where value lands, and whether the outcome still matches the owner mandate.</p></div><div className="grid-3">{features.map(([Icon,title,copy,tag])=><article className="feature" key={title}><div className="feature-icon"><Icon size={20}/></div><h3>{title}</h3><p>{copy}</p><span className="tag">{tag}</span></article>)}</div></section>
<section id="workflow" className="dark-section"><div className="shell"><div className="section-head"><div><span className="eyebrow">Deterministic by design</span><h2>No invisible leap from prompt to signature.</h2></div><p>The model may explain and recommend. It never grants authority. Authority comes from signed policy and fixed validation.</p></div><div className="workflow"><article><span>01 / COMPILE</span><h3>Define the mandate</h3><p>Set program allowlists, value ceilings, destinations, slippage, cadence, and stops.</p></article><article><span>02 / INSPECT</span><h3>Decode the intent</h3><p>Turn an opaque transaction into a readable action graph.</p></article><article><span>03 / SIMULATE</span><h3>Measure the outcome</h3><p>Compare balance changes and behavior against every active rule.</p></article><article><span>04 / ATTEST</span><h3>Publish the receipt</h3><p>Anchor a policy hash and decision reference on devnet.</p></article></div></div></section>
<section id="proof" className="section shell"><div className="section-head"><div><span className="eyebrow">Built for operators</span><h2>A security product that can answer why.</h2></div><p>Every block and approval carries a reason, the exact rule evaluated, and a stable receipt identifier.</p></div><div className="grid-3"><article className="feature"><div className="feature-icon"><Shield size={20}/></div><h3>Default deny</h3><p>Unknown programs stop at the rail instead of inheriting wallet access.</p></article><article className="feature"><div className="feature-icon"><WalletCards size={20}/></div><h3>Wallet-native proof</h3><p>Publish a signed policy receipt on devnet without giving Vowrail custody.</p></article><article className="feature"><div className="feature-icon"><Waypoints size={20}/></div><h3>Portable policy</h3><p>Versioned JSON makes rules reviewable, diffable, and embeddable.</p></article></div></section><section className="cta shell"><div className="cta-card"><h2>Give your agent room to work, not room to improvise.</h2><Link className="button primary" href="/studio">Open policy studio <ArrowRight size={16}/></Link></div></section></main><footer className="footer shell"><span>Vowrail - Solana devnet MVP</span><span>Mandate. Simulate. Prove.</span></footer></>}
