const base=process.env.VOWRAIL_BASE_URL??'https://vowrail.vercel.app';const receipt=process.env.VOWRAIL_RECEIPT;const checks=[];
async function check(name,run){const started=Date.now();try{const detail=await run();checks.push({name,ok:true,latencyMs:Date.now()-started,detail})}catch(error){checks.push({name,ok:false,latencyMs:Date.now()-started,error:error instanceof Error?error.message:String(error)})}}
async function json(path,init){const response=await fetch(base+path,init);const data=await response.json();return{response,data}}
for(const path of['/','/app','/studio','/lab','/receipts','/verify'])await check(`page ${path}`,async()=>{const response=await fetch(base+path);if(!response.ok)throw new Error(`HTTP ${response.status}`);return response.status});
await check('solana devnet rpc',async()=>{const{response,data}=await json('/api/devnet/status');if(!response.ok||!data.online)throw new Error('RPC offline');return{slot:data.slot,latencyMs:data.latencyMs}});
await check('deterministic allow',async()=>{const{data}=await json('/api/evaluate',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({mandateId:'vwr_smoke',provider:'https://provider.vowrail.test/pay',amountUsd:12,spentTodayUsd:40,perCallLimitUsd:35,dailyLimitUsd:250,providerAllowed:true,assetAllowed:true,expiresAt:new Date(Date.now()+60000).toISOString()})});if(data.decision!=='allow')throw new Error(data.reason??data.error);return data.reason});
await check('deterministic deny',async()=>{const{data}=await json('/api/evaluate',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({mandateId:'vwr_smoke',provider:'https://unknown.vowrail.test/pay',amountUsd:12,providerAllowed:false,assetAllowed:true,expiresAt:new Date(Date.now()+60000).toISOString()})});if(data.decision!=='deny')throw new Error('Expected deny');return data.reason});
await check('groq agent reasoning',async()=>{const{response,data}=await json('/api/analyze',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({policy:{name:'Production smoke',maxSol:5,maxSlippageBps:50,dailyLimitSol:25,allowedPrograms:['vowrail'],blockedDestinations:[]},intent:{amountSol:.1,slippageBps:0,program:'vowrail'}})});if(!response.ok||!data.analysis)throw new Error(data.error??'No analysis');if(data.analysis.includes('Add GROQ_API_KEY'))throw new Error('Groq is not configured');return data.analysis.slice(0,120)});
await check('agent preflight trace',async()=>{const{response,data}=await json('/api/agent-run',{method:'POST',headers:{'content-type':'application/json'},body:'{}'});if(!response.ok||!data.readyForWallet)throw new Error(data.error??data.deterministic?.reason??'Preflight failed');if(data.ai?.status!=='live')throw new Error(`Groq status ${data.ai?.status??'missing'}`);if(data.deterministic?.checks?.length!==6)throw new Error('Incomplete deterministic trace');return{runId:data.runId,decision:data.deterministic.reason,ai:data.ai.status}});
await check('http 402 challenge',async()=>{const{response,data}=await json('/api/demo-resource');if(response.status!==402||!data.quote?.mandateHash)throw new Error(`HTTP ${response.status}`);return{amountSol:data.quote.amountSol,mandateHash:data.quote.mandateHash}});
if(receipt)await check('receipt-gated release',async()=>{const{response,data}=await json('/api/demo-resource',{headers:{'x-vowrail-receipt':receipt}});if(!response.ok||data.access!=='granted')throw new Error(data.error??`HTTP ${response.status}`);return{version:data.evidence.version,dataset:data.resource.dataset}});
if(receipt)await check('receipt v2 account proof',async()=>{const{response,data}=await json('/api/verify',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({receipt})});if(!response.ok||!data.verified)throw new Error(data.reason??`HTTP ${response.status}`);if(data.evidence?.receipt!==receipt)throw new Error('Verifier returned a different receipt');return{programId:data.programId,provider:data.evidence.provider,amountSol:data.evidence.amountSol}});
const ok=checks.every(item=>item.ok);console.log(JSON.stringify({ok,base,checkedAt:new Date().toISOString(),checks},null,2));if(!ok)process.exit(1);
